"""intial migration

Revision ID: 471e1656e7d2
Revises:
Create Date: 2019-08-05 15:22:17.640865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471e1656e7d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('site_allowance', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'website',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_table(
        'customer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email_address', sa.String(length=120), nullable=False),
        sa.Column('password', sa.String(length=50), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email_address'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('website')
    op.drop_table('plan')
    # ### end Alembic commands ###
