"""added default renewal date

Revision ID: 65d007435dcf
Revises: 7cecf8a2a0a1
Create Date: 2019-08-06 06:56:43.035931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d007435dcf'
down_revision = '7cecf8a2a0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('renewal_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'renewal_date')
    # ### end Alembic commands ###
