"""added websites M-M relationship to plan

Revision ID: 7cecf8a2a0a1
Revises: 471e1656e7d2
Create Date: 2019-08-06 05:08:53.054739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cecf8a2a0a1'
down_revision = '471e1656e7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customer_websites',
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('website_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
        sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
        sa.PrimaryKeyConstraint('customer_id', 'website_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_websites')
    # ### end Alembic commands ###
